version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      prefix-development: "dev-deps"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/tools/NotionConverter"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps:notion-converter"
      prefix-development: "dev-deps:notion-converter"
      include: "scope"
