name: lint

on:
  pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

        - name: Set up Bun
          uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
          with:
            bun-version: latest

        - name: Install dependencies
          run: bun install

        # BiomeによるLint
        - name: Run Bun lint
          run: bun lint

        # React RouterとTSCによる型チェック
        - name: Run TypeCheck
          run: bun typecheck
