name: lint

on:
  pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

        - name: Set up Bun
          uses: oven-sh/setup-bun@54cb141c5c91e2fdc396be3155a391f28e1822eb # v2.0.1
          with:
            bun-version: latest

        - name: Install dependencies
          run: bun install

        # BiomeとKnipによる静的解析
        - name: Run Bun lint
          run: bun lint

        # React RouterとTSCによる型チェック
        - name: Run TypeCheck
          run: bun typecheck
